### PR TITLE
Disable a2dp-sink, because it is not supported and breaks bt-audio.

### PR DESCRIPTION
**Pull request by Jenna-66**
Should fix bluetooth-audio.
Fetched from https://github.com/LineageOS/android_device_xiaomi_msm8998-common/commit/cc15b2b46d222f5976c88165946967f17a5e1ce3

### CODE REVIEW

**Comment by Dyneteve** [comment]
@jenslody Cam you put it over on gerrit ( review.msm8916.com )

**Comment by Jenna-66** [comment]
I will try.
I never used gerrit before, but like to learn new things.
I just registered at gerrit, but can not add a mail-address (and therefore not push), because my server is down (or at least extremely slow) at the moment. Seems to be a problem of the hoster (hopefully).

**Comment by Jenna-66** [comment]
(Mail-)Server is back, change is online, I hope I did it correctly.

**Comment by Dyneteve** [comment]
Can you close this pr? since the change is on gerrit

**Pull request closed without merging**
